# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
