# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodels',
            name='customid',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
